export enum TagTypes {
  AUTHENTICATION = "AUTHENTICATION",
  PROFILE = "PROFILE",
  POSTS = "POSTS",
  CATEGORIES = "CATEGORIES",
  TAGS = "TAGS",
  USERS = "USERS",
  ROLES = "ROLES",
  PERMISSIONS = "PERMISSIONS",
}
